name: ModelRuns

on:
    push:
      branches:
        - '**'

jobs:
  models:
    name: models
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest, macos-latest]
          python-version: [3.8]
      fail-fast: false
    steps:
      - name: Checkout github
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies (pip)
        run: |
          pip install --upgrade pip wheel
          pip install httpstan
          pip install --pre pystan
      
      - name: Inject prints
        run: |
          python -c "import stan;print(stan)"
          python -c "import httpstan;print(httpstan)"
          find /opt/hostedtoolcache/Python -type f -wholename "model.py" 2>/dev/null | xargs sed -i 's/msg.ParseFromString(fit_bytes[pos : pos + next_pos])/print(pos, next_pos, fit_bytes[pos : pos + next_pos], fit_bytes);msg.ParseFromString(fit_bytes[pos : pos + next_pos])/ w /dev/stdout'
      
      - name: Check versions
        run: |
          python -c 'import httpstan;print("HTTPStan version: {}".format(httpstan.__version__))'
          python -c 'import stan;print("PyStan version: {}".format(stan.__version__))'

      - name: Run models
        run: |
          python scripts/run_models.py
